apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  servers.json: |
    {
        "Servers": {
          "1": {
            "Name": "PostgreSQL DB",
            "Group": "Servers",
            "Port": 5432,
            "Username": "postgres",
            "Password": "password"
            "Host": "postgres.default.svc",
            "SSLMode": "prefer",
            "MaintenanceDB": "postgres"
          }
        }
    }
